name: Rust
on: [ push ]
jobs:
  test:
    strategy:
      matrix:
        os: [ { name: Windows, os: windows-latest }, { name: Ubuntu, os: ubuntu-latest } ]
    name: Tests on ${{ matrix.os.name }}
    runs-on: ${{ matrix.os.os }}
    steps:
    - name: Use actions/checkout@v1
      uses: actions/checkout@v1

    - name: Run cargo test
      run: cargo test